FROM %%IMAGE_NAME%%
RUN apt update && \
    apt -y --no-install-recommends --no-install-suggests install libjemalloc2 curl && \
    apt clean && rm -rf /var/lib/apt/lists/*
ENV LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.2
LABEL com.rbkmoney.%%SERVICE_NAME%%.parent=%%IMAGE_NAME%%  \
    com.rbkmoney.%%SERVICE_NAME%%.branch=%%BRANCH%%  \
    com.rbkmoney.%%SERVICE_NAME%%.commit_hash=%%COMMIT_HASH%%  \
